{{ if .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Chart.Name }}-backup
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "backup"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "{{ .Chart.Name }}-{{ .Values.backup.serviceaccount_suffix }}"
imagePullSecrets:
- name: gcrinventi
{{- end }}
