{{ if .Values.backup.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Chart.Name }}-backup
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "backup"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Chart.Name }}-pod-read-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
  - apiGroups:
      - extensions
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - update
{{- end }}
