{{ if .Values.backup.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Chart.Name }}-backup
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "backup"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ .Chart.Name }}-backup-rolebinding
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-{{ .Values.backup.serviceaccount_suffix }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-pod-read-role
{{- end }}
